spring.application.name=flexit-backend
spring.data.mongodb.uri=mongodb+srv://prabodalakshan02_db_user:Flexit2026@cluster0.fsvizhl.mongodb.net/Flexit?retryWrites=true&w=majority&authSource=admin&connectTimeoutMS=10000&serverSelectionTimeoutMS=10000
server.port=8081
google.oauth.client-id=56782348760-r8g03gb9klan6hufislau31mbrqhr4lc.apps.googleusercontent.com