spring.application.name=flexit-backend
spring.mongodb.uri=mongodb+srv://prabodalakshan02_db_user:Flexit2026@cluster0.fsvizhl.mongodb.net/Flexit?retryWrites=true&w=majority&authSource=admin&connectTimeoutMS=10000&serverSelectionTimeoutMS=10000
server.port=8080